### ISSUE TITLE
Profile/person creation seems to have no effect

### ISSUE THREAD

**Issue by dsoprea** [klaviyo/klaviyo-python-sdk#10]
I can create a profile using the API directly:

```
curl \
    --request POST \
    --url https://a.klaviyo.com/api/identify \
    --header 'accept: text/html' \
    --header 'content-type: application/x-www-form-urlencoded' \
    --data 'data={"token": "<SECRET>","properties": {"$email":"abc@def.com"}}'
```

This prints `1`.

However, the client doesn't do anything:

```python
data = {
    'email': 'abc@def.com'
}

r = kc.TrackIdentify.identify_post(data=data)
```

This returns `0`.

I also tried using "$email" as the field name in parity with the cURL example, but it didn't make a difference.

How do I create a profile using the client?

**Comment by jon-batscha** [comment]
Hey, thanks for reaching out!

For `track`/`identify` endpoints, the `data` object needs to be the same as it is for the curl request. 

You are definitely not the first developer to flag this behavior as inconsistent, so we are actively looking into reworking the interface to make the behavior clearer. We really appreciate this type of feedback, so please reach out again if you run into any further issues.


Cheers,
Jon

**Comment by dsoprea** [comment]
It would be appreciated if you'd provide an example just to remove all ambiguity. Per my message, I tried doing that. I also tried sending the verbatim string but got "Connection reset by peer".

**Comment by jon-batscha** [comment]
```python
data={"token": "<PUBLIC_KEY>","properties": {"$email":"abc@def.com"}}

r = kc.TrackIdentify.identify_post(data=data)
```

NOTE: for the `identify`/`track` endpoints, use your 6-character Public API Key / Site ID as the token, NOT your Private API Key

Please let me know if this resolves your issue. Cheers!

**Comment by dsoprea** [comment]
Yeah. That worked.

What's the function of the public key versus the private key? In the cURL example, the private key worked fine.



Runnable example that removes ambiguity about whether that's supposed to be text or a dictionary:
```
import klaviyo_sdk

private_key = "<...>"
public_key = '<...>'

kc = klaviyo_sdk.Client(private_key)

email = 'abc@def.com'
data = {"token": public_key,"properties": {"$email":email}}
r = kc.TrackIdentify.identify_post(data=data)
print(r)
```

As with cURL, the response is a string. Seemingly "1" every time.

**Comment by jon-batscha** [comment]
These write-only identify/track endpoints in our legacy/stable API are unique in that they need to be secure for use onsite/client-side, so they cannot use the private key. Likewise for these specific endpoints the response is 1 or 0, to indicate if the request was properly formatted.

You are not the first to raise the point that this design is not intuitive. We have incorporated this feedback in our brand new API (currently in [Beta](https://developers.klaviyo.com/en/v2022-09-07.pre/reference/api-overview), in General Availability shortly)

In our new API, there are 2 versions for each of these (serverside tracking for [profiles](https://developers.klaviyo.com/en/v2022-09-07.pre/reference/create_profile) and [events](https://developers.klaviyo.com/en/v2022-09-07.pre/reference/create_event), vs [client-side tracking](https://developers.klaviyo.com/en/v2022-09-07.pre/reference/create_client_subscription)). Likewise, in our new API, the error responses are now informative.

**Comment by dsoprea** [comment]
Thanks for clarifying.

**Comment by dsoprea** [comment]
Given our [currently] simple requirements and the inconsistent and no-added-value nature of the Python client, we just hit the API directly. I'm sharing that integration here until you can officially release that new API and client.

https://gist.github.com/dsoprea/8105fe491a92114574e6640fa2cf5963
