### ISSUE TITLE
Client returns 404 for calls

### ISSUE THREAD

**Issue by mattkantor** [klaviyo/klaviyo-python-sdk#2]
Sending a simple call reverts to calling http as a GET with unknown Content type (for async false) .  Always returns HTML of the Klaviyo 404 page. 

Code:

`
client = Client(api_key=self.credentials['api_key'], max_delay=1, max_retries=1)
client.ListsSegments.add_members(list_id, body=user_adds, async_req=False)
`

DEBUG PRE Send:
`
URL = https://a.klaviyo.com/api/v2/list/6323/members
method = POST
headers = [('api_key', 'pk_xxx')]
{'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'klaviyo-python/1.0.1.20211126'}
`

RESPONSE:
`
swagger_client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 02 Feb 2022 20:39:40 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding, Cookie', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Set-Cookie': 'xxx=; path=/; expires=Wed, 02-Feb-22 21:09:40 GMT; domain=.klaviyo.com; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare', 'CF-RAY': '6d763aedebfe2910-ORD'})
HTTP response body: b'<!DOCTYPE html>\n<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\n\n<title>Oops (Error 404) - Klaviyo</title>\n<link rel="shortcut icon" href="/media/Favicon-16by16.png" />\n<style type="text/css">\n  body {\n    font-family: \'Lucida Grande\', sans-serif;\n........
`

Python 3.8

**Comment by mattkantor** [comment]
Sorry looks like a 404 from a bad list ID.

**Comment by mangoceylon** [comment]
Thanks for closing it, no worries!

**Comment by mattkantor** [comment]
I would say though that returning text/html to a JSON post request isn't ideal, although I know this is a server issue and not an SDK issue.
