### ISSUE TITLE
Error when deploying to AWS Lambda

### ISSUE THREAD

**Issue by lmiguelmh** [klaviyo/klaviyo-python-sdk#3]
I have a problem when trying to use the Klaviyo SDK on AWS Lambda. 

I am using the latest version published on pip: 
https://pypi.org/project/klaviyo-sdk/

The instantiation of the `Client` class fails (it runs fine locally).
Looking on the stack I see it fails here:

```
  File "/var/lang/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 38] Function not implementedException
```

Surely this is because [AWS Lambda execution environment does not have /dev/shm support](https://aws.amazon.com/blogs/compute/parallel-processing-in-python-with-aws-lambda/), so you can’t use multiprocessing.Queue or multiprocessing.Pool.

**Is there a workaround or a way to disable the use of multiprocessing from Klaviyo SDK?**

*Complete stack*
```
[Errno 38] Function not implemented
Traceback (most recent call last):
...
  File "/opt/python/tentrr/klaviyo.py", line 98, in __init__
    self.client = Client(self.token, max_delay=60, max_retries=3)
  File "/opt/python/klaviyo_sdk/wrapper.py", line 41, in __init__
    setattr(self,subclient_name,eval(f'swagger_client.{subclient_name}(swagger_client.ApiClient(configuration))'))
  File "<string>", line 1, in <module>
  File "/opt/python/swagger_client/api_client.py", line 68, in __init__
    self.pool = ThreadPool()
  File "/var/lang/lib/python3.9/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/var/lang/lib/python3.9/multiprocessing/pool.py", line 196, in __init__
    self._change_notifier = self._ctx.SimpleQueue()
  File "/var/lang/lib/python3.9/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/var/lang/lib/python3.9/multiprocessing/queues.py", line 342, in __init__
    self._rlock = ctx.Lock()
  File "/var/lang/lib/python3.9/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/var/lang/lib/python3.9/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/var/lang/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 38] Function not implementedException ignored in: <function ApiClient.__del__ at 0x7f95ab961310>
Traceback (most recent call last):
File "/opt/python/swagger_client/api_client.py", line 78, in __del__
self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
```

**Comment by mangoceylon** [comment]
Thanks for raising this, it looks like this may be somewhat related to another issue we are tracking: https://github.com/klaviyo/klaviyo-python-sdk/issues/1

In that issue there is an error with cleaning up pools related to CPython, so using pools are currently creating multiple errors.

We will investigate and provide guidance.

**Comment by lmiguelmh** [comment]
The problem related with #1 happens when the pool is closing. 

The problem posted in this issue happens because AWS Lambda's Python environment does not support Python's multiprocessing module. We can't instantiate nor use any methods of the Client class.

**Comment by mangoceylon** [comment]
We understand, the fix may be to remove pooling all together is what was meant.

**Comment by lmiguelmh** [comment]
Thanks for your support... 
I solved the issue:

1. I had to create a [custom Klaviyo API Client class](https://gist.github.com/lmiguelmh/0fb8e2537739a75237aef21fe8cc864a). If you guys want I can make a PR.

2. Call the internal API directly:

```
configuration = Configuration()
configuration.api_key["api_key"] = self.token
api = TrackIdentifyApi(CustomApiClient(configuration))

data = {
    "token": token,
    "properties": properties
}
response = api.identify_post(async_req=False, data=data_str)
```

**Comment by mangoceylon** [comment]
The custom API Klaviyo Client class you created by commenting out the pooling should work, but that file is auto-generated by the engine we use to create the client library, so unfortunately it is not as simple as using that as a PR. That should work for your purposes, we will look into modifying our engine to potentially create another argument on client init to disable pooling and avoid this issue.

**Comment by lmiguelmh** [comment]
Yeah, just add `async_req` argument to the constructor.

**Comment by mangoceylon** [comment]
As you were able to un-block yourself, going to close this issue. Will update if we release a new generated SDK with the ability to disable pooling.
