### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by 0xE111** [klaviyo/klaviyo-python-sdk#8]
This library is written without respect to python best practices. There are several severe issues, like not using timeouts and using `eval`. Detailed code review is available here: https://breakpoint.black/review/f1fdb615-6305-4812-a6fb-003b97ef9bee/
Writing clear and reliable code is showing company's respect to developers.

**Comment by jon-batscha** [comment]
Hey! 

Thanks so much for the thorough code review, just pushed the newest release incorporating your valuable feedback.

Klaviyo is dedicated to improving our developer ecosystem, and we could not do that without feedback from you and the rest of the community. Please do reach out if you have any more feedback or questions for us. And if you want to stay up-to-date on our latest releases, I encourage to sign-up for our developer newsletter in the footer of our developer site: [developers.klaviyo.com](http://developers.klaviyo.com/)

Thanks again!

Cheers,
Jon
